all:	
	g++ receiver1.c -o exe_receiver1
	g++ sender1.c -o exe_sender1
	g++ receiver2.c -o exe_receiver2
	g++ sender2.c -o exe_sender2
	g++ receiver3.c -o exe_receiver3
	g++ sender3.c -o exe_sender3
clean:
	rm exe_*
